In [2]:
import pandas as pd
import numpy as np

daten = {
    "kunde":     ["K01","K02","K03","K04","K05","K06","K07","K08","K09","K10"],
    "alter":     [34, 52, 23, 45, 61, 29, 38, 47, 26, 55],
    "einkommen": [3200, 5100, 1800, 4200, 2900, 2400, 3900, np.nan, 2100, 6000],
    "kredit":    [8000, 15000, 5000, 12000, 7000, 9000, 10000, 20000, 4000, 25000],
    "laufzeit":  [24, 36, 12, 48, 24, 36, 24, 60, 12, 48],
    "zweck":     ["Auto","Haus","Konsum","Haus","Auto","Konsum","Auto","Haus","Konsum","Haus"],
    "ausfall":   [0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
}
df = pd.DataFrame(daten)
df

  kunde  alter  einkommen  kredit  laufzeit   zweck  ausfall
0   K01     34     3200.0    8000        24    Auto        0
1   K02     52     5100.0   15000        36    Haus        0
2   K03     23     1800.0    5000        12  Konsum        1
3   K04     45     4200.0   12000        48    Haus        0
4   K05     61     2900.0    7000        24    Auto        0
5   K06     29     2400.0    9000        36  Konsum        1
6   K07     38     3900.0   10000        24    Auto        0
7   K08     47        NaN   20000        60    Haus        1
8   K09     26     2100.0    4000        12  Konsum        1
9   K10     55     6000.0   25000        48    Haus        0

In [3]:
#A1: Überblick - Anzahl Spalten, Daten, Typ je Spalte
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   kunde      10 non-null     str
 1   alter      10 non-null     int64
 2   einkommen  9 non-null      float64
 3   kredit     10 non-null     int64
 4   laufzeit   10 non-null     int64
 5   zweck      10 non-null     str
 6   ausfall    10 non-null     int64
dtypes: float64(1), int64(4), str(2)
memory usage: 692.0 bytes

In [4]:
#A2:Auswählen & Filtern
df.loc[df['ausfall'] == 1, ['kunde', 'einkommen', 'kredit']]

  kunde  einkommen  kredit
2   K03     1800.0    5000
5   K06     2400.0    9000
7   K08        NaN   20000
8   K09     2100.0    4000

In [5]:
#A3: Kennzahlen
df.ausfall.mean()

np.float64(0.4)

In [6]:
#A4: Gruppieren
df.groupby('zweck').ausfall.mean()

zweck
Auto      0.00
Haus      0.25
Konsum    1.00
Name: ausfall, dtype: float64

In [7]:
#A5: Fehlende Werte
display(df.einkommen.isnull().sum())
df['einkommen'] = df.einkommen.fillna(df.einkommen.mean())
display(df)

np.int64(1)

  kunde  alter    einkommen  kredit  laufzeit   zweck  ausfall
0   K01     34  3200.000000    8000        24    Auto        0
1   K02     52  5100.000000   15000        36    Haus        0
2   K03     23  1800.000000    5000        12  Konsum        1
3   K04     45  4200.000000   12000        48    Haus        0
4   K05     61  2900.000000    7000        24    Auto        0
5   K06     29  2400.000000    9000        36  Konsum        1
6   K07     38  3900.000000   10000        24    Auto        0
7   K08     47  3511.111111   20000        60    Haus        1
8   K09     26  2100.000000    4000        12  Konsum        1
9   K10     55  6000.000000   25000        48    Haus        0

In [12]:
#A6: Neue Spalte + Sortieren
df['rate'] = df.kredit / df.laufzeit
df.sort_values('rate', ascending=False).head(3)

  kunde  alter  einkommen  kredit  laufzeit zweck  ausfall        rate
9   K10     55     6000.0   25000        48  Haus        0  520.833333
1   K02     52     5100.0   15000        36  Haus        0  416.666667
6   K07     38     3900.0   10000        24  Auto        0  416.666667

In [14]:
#A7: Umbenennen
renamed = df.rename(columns={'ausfall': 'ziel'})
display(renamed)
display(df)

  kunde  alter    einkommen  kredit  laufzeit   zweck  ziel        rate
0   K01     34  3200.000000    8000        24    Auto     0  333.333333
1   K02     52  5100.000000   15000        36    Haus     0  416.666667
2   K03     23  1800.000000    5000        12  Konsum     1  416.666667
3   K04     45  4200.000000   12000        48    Haus     0  250.000000
4   K05     61  2900.000000    7000        24    Auto     0  291.666667
5   K06     29  2400.000000    9000        36  Konsum     1  250.000000
6   K07     38  3900.000000   10000        24    Auto     0  416.666667
7   K08     47  3511.111111   20000        60    Haus     1  333.333333
8   K09     26  2100.000000    4000        12  Konsum     1  333.333333
9   K10     55  6000.000000   25000        48    Haus     0  520.833333

  kunde  alter    einkommen  kredit  laufzeit   zweck  ausfall        rate
0   K01     34  3200.000000    8000        24    Auto        0  333.333333
1   K02     52  5100.000000   15000        36    Haus        0  416.666667
2   K03     23  1800.000000    5000        12  Konsum        1  416.666667
3   K04     45  4200.000000   12000        48    Haus        0  250.000000
4   K05     61  2900.000000    7000        24    Auto        0  291.666667
5   K06     29  2400.000000    9000        36  Konsum        1  250.000000
6   K07     38  3900.000000   10000        24    Auto        0  416.666667
7   K08     47  3511.111111   20000        60    Haus        1  333.333333
8   K09     26  2100.000000    4000        12  Konsum        1  333.333333
9   K10     55  6000.000000   25000        48    Haus        0  520.833333